---
title: "Figure Assignment"
---
Distinct µ-opioid ensembles trigger positive and negative fentanyl reinforcement 

Figure 1 Data Set
```{r}
library(tidyverse)
library(ggthemes)

theme_set(theme_few() + # set the theme
            theme(text = element_text(size = 9)))

library(ggpubr)
library(ggsignif)
library(patchwork)

fentanyl_data = read.csv("/Users/michellebach/Documents/GitHub/Figure Assignment/Compiled_Data.csv")

fentanyl_data

# str(fentanyl_data)
```

Figure 1C
```{r}
xorder <- c("SalNal", "Saline", "Naloxone") # x axis order
```


```{r} 
# graph with num of jumps
panel1 <- ggplot(data = fentanyl_data,
       mapping = aes(x = factor(Condition, xorder),
                     y = Jump)) + 
  geom_boxplot(aes(fill = Condition),
               width = 0.5,
               outlier.color = "white",
               show.legend = FALSE) +
  geom_jitter(shape = "circle",
             color = "black",
             size = 2.5,
             alpha = 0.3,
             show.legend = FALSE,
             width=.1, 
             height=0) +
  stat_summary(fun.min = min, 
               fun.max = max, 
               geom = "errorbar", 
               width = 0.1) +
  scale_y_continuous(limits=c(0, 150)) +
  xlab(" ") +
  ylab("No. of Jumps") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(fill = "")

panel1 <- panel1 + scale_fill_manual(values = c(Naloxone = "orange",
                                                Saline = "lightblue",
                                                SalNal = "lightgreen"))

# condition_comparisons <- list(c("SalNal", "Naloxone"), c("Naloxone", "Saline"))

panel1 <- panel1 + geom_signif(comparisons = list(c("SalNal", "Naloxone")),
                               map_signif_level = TRUE,
                               y_position = c(127, 250)) +
  geom_signif(comparisons = list(c("Saline", "Naloxone")),
              map_signif_level = TRUE,
              y_position = c(140, 250))

panel1
```

```{r}
xorder <- c("SalNal", "Saline", "Naloxone") # x axis order

# immobility time spent
panel2 <- ggplot(data = fentanyl_data,
       mapping = aes(x = factor(Condition, xorder),
                     y = Immobility)) + 
  geom_boxplot(aes(fill = Condition),
               width = 0.5,
               outlier.color = "white",
               na.rm=TRUE) +
  geom_jitter(shape = "circle",
             color = "black",
             size = 2.5,
             alpha = 0.3,
             na.rm=TRUE,
             width=0.3,
             height=0) +
  stat_summary(fun.min = min, 
               fun.max = max, 
               geom = "errorbar", 
               width = 0.1,
               na.rm=TRUE) +
  scale_y_continuous(limits=c(0, 15)) +
  xlab(" ") +
  ylab("Immobility time (min)") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(fill = "Termination") +
  theme(legend.position = c(0.35, 0.48),
        legend.title = element_text(size = 9))
  
panel2 <- panel2 + scale_fill_manual(values = c(Naloxone = "orange",
                                      Saline = "lightblue",
                                      SalNal = "lightgreen"))

panel2 <- panel2 + 
  geom_signif(comparisons = list(c("SalNal", "Naloxone")),
                               map_signif_level = TRUE,
                               y_position = c(10, 13)) +
  geom_signif(comparisons = list(c("Saline", "Naloxone")),
              map_signif_level = TRUE,
              annotations = c("***"),
              y_position = c(12, 14))

panel2 
```


```{r}
# combine panels
fig1c <- panel1 + panel2

fig1c
```

